### ISSUE TITLE
OSX 10.13.4无法运行

### ISSUE THREAD

**Issue by rekcah1986** [EllanJiang/StarForce#8]
直接把Scene和Game面板卡掉了，只剩下一个黑屏……
Download failure, download serial id '0', download path '/Users/Prism/Library/Application Support/Jiang Yin/Star Force/version.dat', download uri 'http://gameframework.cn/starforce/resources/0_1_0_1/osx/version.0c98cd0b.dat', error message 'Timeout'.

**Comment by EllanJiang** [comment]
这貌似是Unity的一个BUG，运行时修改一下窗口布局就好了。
